In [1]:
import kagglehub
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

# Download latest version
path = kagglehub.dataset_download("atharvasoundankar/futuristic-smart-city-citizen-activity-dataset")

print("Path to dataset files:", path)

DATA_DIR = Path("..") / "data"
file_path = DATA_DIR / "smart_city_citizen_activity.csv"

from kagglehub import KaggleDatasetAdapter

file_path = "smart_city_citizen_activity.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "atharvasoundankar/futuristic-smart-city-citizen-activity-dataset",
  file_path,)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: /Users/tiana/.cache/kagglehub/datasets/atharvasoundankar/futuristic-smart-city-citizen-activity-dataset/versions/1

/var/folders/fm/zzjr3l5d7nl5vdp9q79tzwvh0000gn/T/ipykernel_7575/500265655.py:19: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

In [2]:
print("Shape:", df.shape)
df.head()

Shape: (1000, 15)

,Citizen_ID,Age,Gender,Mode_of_Transport,Work_Hours,Shopping_Hours,Entertainment_Hours,Home_Energy_Consumption_kWh,Charging_Station_Usage,Carbon_Footprint_kgCO2,Steps_Walked,Calories_Burned,Sleep_Hours,Social_Media_Hours,Public_Events_Hours
0,1001,56,Female,Walking,5,2,0,5.32,0,44.70,15635,975,9.2,5.8,0.5
1,1002,69,Male,Bicycle,0,2,2,2.19,0,92.39,1671,455,8.1,5.5,1.9
2,1003,46,Male,Bike,0,4,0,4.68,0,78.57,1777,324,4.7,3.8,2.8
3,1004,32,Male,Car,7,2,3,3.42,0,55.46,4022,537,4.9,3.5,0.5
4,1005,60,Male,Walking,3,3,1,2.79,0,98.95,19244,1414,6.6,2.2,0.5

In [3]:
df.info(), df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Citizen_ID                   1000 non-null   int64
 1   Age                          1000 non-null   int64
 2   Gender                       1000 non-null   object
 3   Mode_of_Transport            1000 non-null   object
 4   Work_Hours                   1000 non-null   int64
 5   Shopping_Hours               1000 non-null   int64
 6   Entertainment_Hours          1000 non-null   int64
 7   Home_Energy_Consumption_kWh  1000 non-null   float64
 8   Charging_Station_Usage       1000 non-null   int64
 9   Carbon_Footprint_kgCO2       1000 non-null   float64
 10  Steps_Walked                 1000 non-null   int64
 11  Calories_Burned              1000 non-null   int64
 12  Sleep_Hours                  1000 non-null   float64
 13  Social_Media_Hours           1000 non-null   float64
 14  Public_Events_Hours          1000 non-null   float64
dtypes: float64(5), int64(8), object(2)
memory usage: 117.3+ KB

(None,
         Citizen_ID         Age   Work_Hours  Shopping_Hours  \
 count  1000.000000  1000.00000  1000.000000     1000.000000
 mean   1500.500000    43.81900     4.397000        2.024000
 std     288.819436    14.99103     2.870127        1.421071
 min    1001.000000    18.00000     0.000000        0.000000
 25%    1250.750000    31.00000     2.000000        1.000000
 50%    1500.500000    44.00000     4.000000        2.000000
 75%    1750.250000    56.00000     7.000000        3.000000
 max    2000.000000    69.00000     9.000000        4.000000

        Entertainment_Hours  Home_Energy_Consumption_kWh  \
 count          1000.000000                  1000.000000
 mean              1.532000                     5.996900
 std               1.102811                     2.302009
 min               0.000000                     2.000000
 25%               1.000000                     4.050000
 50%               2.000000                     5.870000
 75%               2.250000                     8.010000
 max               3.000000                     9.990000

        Charging_Station_Usage  Carbon_Footprint_kgCO2  Steps_Walked  \
 count              1000.00000             1000.000000   1000.000000
 mean                  0.29400               54.416840  10514.961000
 std                   0.45582               26.062576   5588.931531
 min                   0.00000               10.020000   1011.000000
 25%                   0.00000               31.717500   5679.500000
 50%                   0.00000               53.665000  10448.500000
 75%                   1.00000               77.865000  15377.500000
 max                   1.00000               99.930000  19972.000000

        Calories_Burned  Sleep_Hours  Social_Media_Hours  Public_Events_Hours
 count       1000.00000  1000.000000         1000.000000          1000.000000
 mean         818.61300     6.987000            3.007500             1.503600
 std          302.49261     1.710923            1.706249             0.874226
 min          171.00000     4.000000            0.000000             0.000000
 25%          581.00000     5.500000            1.600000             0.800000
 50%          805.00000     7.000000            3.000000             1.500000
 75%         1070.00000     8.400000            4.400000             2.300000
 max         1447.00000    10.000000            6.000000             3.000000  )

In [ ]:
df_clean = df["Citizen_ID","Age","Work_Hours","Shopping_Hours","Entertainment_Hours", "Home_Energy_Consumption_kWh", "Charging_Station_Usage", "Steps_Walked"]

In [6]:
df['Gender'] = df['Gender'].astype(float)
df.head()

ValueError: could not convert string to float: 'Female'

In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

X = pd.get_dummies(
    df[["Citizen_ID","Age","Work_Hours","Shopping_Hours","Entertainment_Hours", "Home_Energy_Consumption_kWh", "Charging_Station_Usage", "Steps_Walked"]],
    drop_first=True
)
y = df["Carbon_Footprint_kgCO2"]

lr = LinearRegression().fit(X, y)

print(lr.coef_)

# intercept + coefficients 
coef_df = pd.DataFrame({"coef": lr.coef_}, index=X.columns).round(1)
coef_df = coef_df.sort_index()  # sort by index (feature name)

print("Intercept:", round(lr.intercept_, 1))
display(coef_df)
print("R^2:", lr.score(X, y))

[-1.04208460e-03  5.81677049e-02  1.38369645e-01 -8.26190360e-01
 -6.62844137e-01  1.23918487e-01  4.94303699e-01  5.95690413e-05]
Intercept: 54.0

                             coef
Age                           0.1
Charging_Station_Usage        0.5
Citizen_ID                   -0.0
Entertainment_Hours          -0.7
Home_Energy_Consumption_kWh   0.1
Shopping_Hours               -0.8
Steps_Walked                  0.0
Work_Hours                    0.1

R^2: 0.004639956376210619

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [8]:
#  PREDICT for a list of observations --------------------------------------
new_obs = [
    {"Age": 5,  "Charging_Station_Usage": 20,  "Entertainment_Hours": 6,  "Home_Energy_Consumption_kWh": 5, "Shopping_Hours": 2,"Work_Hours": 3},
    {"Age": 12, "Charging_Station_Usage": 52,  "Entertainment_Hours": 3, "Home_Energy_Consumption_kWh": 6, "Shopping_Hours": 2, "Work_Hours": 9},
    {"Age": 25, "Charging_Station_Usage": 87, "Entertainment_Hours": 5, "Home_Energy_Consumption_kWh": 3, "Shopping_Hours": 4, "Work_Hours": 0},
]
# or read the data from a file, like we read the original data: df = pd.read_csv("../data/professors.csv")


new_df = pd.DataFrame(new_obs)
X_new = pd.get_dummies(new_df, drop_first=True)
X_cols = X.columns  
# Align dummy columns to training design matrix. 
X_new = X_new.reindex(columns=X_cols, fill_value=0)

pred = lr.predict(X_new)
new_df["Carbon_Footprint_kgCO2"] = pred.round(0)
new_df

,Age,Charging_Station_Usage,Entertainment_Hours,Home_Energy_Consumption_kWh,Shopping_Hours,Work_Hours,Carbon_Footprint_kgCO2
0,5,20,6,5,2,3,60.0
1,12,52,3,6,2,9,79.0
2,25,87,5,3,4,0,92.0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression

# 1) Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2) Fit on TRAIN only
lr = LinearRegression().fit(X_train, y_train)

# 3) Evaluate on TEST
y_pred = lr.predict(X_test)
r2  = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred)
print(r2)
print(rmse)

NameError: name 'X_temp' is not defined

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score, cross_val_predict
from sklearn.metrics import mean_squared_error

# --- K-fold CV ---
cv = KFold(n_splits=10, shuffle=True, random_state=0)

# R^2 across folds
cv_r2 = cross_val_score(lr, X, y, cv=cv, scoring="r2")
print(f"CV R^2 (mean ± sd): {cv_r2.mean():.3f} ± {cv_r2.std():.3f}")

# RMSE across folds (use negative MSE scores)
cv_mse = cross_val_score(lr, X, y, cv=cv, scoring="neg_mean_squared_error")
#cross_val_score always tries to maximize the score (higher = better), hence neg
cv_rmse = np.sqrt(-cv_mse)
print(f"CV RMSE (mean ± sd): {cv_rmse.mean():.1f} ± {cv_rmse.std():.1f}")

# Optional: cross-validated predictions for diagnostics
y_pred_cv = cross_val_predict(lr, X, y, cv=cv)
resid_cv = y - y_pred_cv
print("CV residuals summary (mean, sd):", resid_cv.mean().round(2), resid_cv.std().round(2))

CV R^2 (mean ± sd): -0.024 ± 0.030
CV RMSE (mean ± sd): 26.2 ± 1.1
CV residuals summary (mean, sd): 0.02 26.23

In [14]:


from sklearn.preprocessing import StandardScaler
#Fit scaler on training data (do this once after training)
scaler = StandardScaler()
scaler.fit(X_train)
# save the scaler for later use
import joblib
joblib.dump(scaler, 'scaler.joblib')

['scaler.joblib']

In [16]:
%pip install mlflow

Collecting mlflow
  Downloading mlflow-3.10.0-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-skinny==3.10.0 (from mlflow)
  Downloading mlflow_skinny-3.10.0-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.0 (from mlflow)
  Downloading mlflow_tracing-3.10.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting Flask<4 (from mlflow)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Downloading cryptography-46.0.5-cp311-abi3-macosx_10_9_universal2.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<26 (from mlflow)
  Downloading gunicorn-25.1.0-py3-none-any.whl.metadata (5.5 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (3.10.6)
Requirement already satisfied: numpy<3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (2.3.2)
Collecting pyarrow<24,>=4.0.0 (from mlflow)
  Downloading pyarrow-23.0.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.1 kB)
Requirement already satisfied: scikit-learn<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.7.2)
Requirement already satisfied: scipy<2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow) (1.16.2)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.48-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Requirement already satisfied: cachetools<8,>=5.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (8.3.1)
Collecting cloudpickle<4 (from mlflow-skinny==3.10.0->mlflow)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.0->mlflow)
  Downloading databricks_sdk-0.96.0-py3-none-any.whl.metadata (40 kB)
Collecting fastapi<1 (from mlflow-skinny==3.10.0->mlflow)
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.10.0->mlflow)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (8.7.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (1.39.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (1.39.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (1.39.0)
Requirement already satisfied: packaging<27 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (25.0)
Requirement already satisfied: protobuf<7,>=3.12.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (6.33.0)
Requirement already satisfied: pydantic<3,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (1.2.1)
Requirement already satisfied: pyyaml<7,>=5.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.10.0->mlflow)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from mlflow-skinny==3.10.0->mlflow) (0.38.0)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: cffi>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow) (2.43.0)
Requirement already satisfied: urllib3>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Collecting starlette>=0.46.0 (from fastapi<1->mlflow-skinny==3.10.0->mlflow)
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: typing-inspection>=0.4.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from fastapi<1->mlflow-skinny==3.10.0->mlflow) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.10.0->mlflow)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=3.1.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from Flask<4->mlflow) (3.1.3)
Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.0->mlflow)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.0->mlflow)
  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow) (4.9.1)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.7-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.0->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (4.60.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib<4->mlflow) (3.2.5)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.0->mlflow) (0.60b0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.0->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.0->mlflow) (2025.10.5)
Requirement already satisfied: pyasn1>=0.1.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.0->mlflow) (0.6.1)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn<2->mlflow) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: h11>=0.8 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from uvicorn<1->mlflow-skinny==3.10.0->mlflow) (0.16.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (2.23)
Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.14)
Requirement already satisfied: anyio<5,>=3.6.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.0->mlflow) (4.11.0)
Requirement already satisfied: sniffio>=1.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.0->mlflow) (1.3.1)
Downloading mlflow-3.10.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 4.7 MB/s  0:00:02m0:00:010:01m
Downloading mlflow_skinny-3.10.0-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 1.9 MB/s  0:00:01 eta 0:00:01
Downloading mlflow_tracing-3.10.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 2.2 MB/s  0:00:00 eta 0:00:01
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-46.0.5-cp311-abi3-macosx_10_9_universal2.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 2.0 MB/s  0:00:03m0:00:0100:01
Downloading databricks_sdk-0.96.0-py3-none-any.whl (813 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 814.0/814.0 kB 2.1 MB/s  0:00:0036m-:--:--
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
Downloading fastapi-0.135.1-py3-none-any.whl (116 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Downloading flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.7-py3-none-any.whl (207 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading gunicorn-25.1.0-py3-none-any.whl (197 kB)
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
Downloading pyarrow-23.0.1-cp313-cp313-macosx_12_0_arm64.whl (34.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.2/34.2 MB 2.4 MB/s  0:00:14m0:00:0100:01
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
Downloading smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading sqlalchemy-2.0.48-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 2.9 MB/s  0:00:00 eta 0:00:01
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading starlette-0.52.1-py3-none-any.whl (74 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: huey, sqlparse, sqlalchemy, smmap, pyarrow, prettytable, Mako, itsdangerous, gunicorn, graphql-core, cloudpickle, blinker, annotated-doc, starlette, graphql-relay, gitdb, Flask, docker, cryptography, alembic, skops, graphene, gitpython, Flask-CORS, fastapi, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29/29 [mlflow]28/29 [mlflow]skinny]]
Successfully installed Flask-3.1.3 Flask-CORS-6.0.2 Mako-1.3.10 alembic-1.18.4 annotated-doc-0.0.4 blinker-1.9.0 cloudpickle-3.1.2 cryptography-46.0.5 databricks-sdk-0.96.0 docker-7.1.0 fastapi-0.135.1 gitdb-4.0.12 gitpython-3.1.46 graphene-3.4.3 graphql-core-3.2.7 graphql-relay-3.2.0 gunicorn-25.1.0 huey-2.6.0 itsdangerous-2.2.0 mlflow-3.10.0 mlflow-skinny-3.10.0 mlflow-tracing-3.10.0 prettytable-3.17.0 pyarrow-23.0.1 skops-0.13.0 smmap-5.0.2 sqlalchemy-2.0.48 sqlparse-0.5.5 starlette-0.52.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [17]:


import mlflow
import mlflow.sklearn
import shutil

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline

import os 

# Remove corrupted mlruns directory if it exists
#if os.path.exists("./mlruns"):
    #shutil.rmtree("./mlruns")

# Create mlruns directory
os.makedirs("./mlruns", exist_ok=True)
# Set up local tracking URI (creates a 'mlruns' folder in your current directory)
mlflow.set_tracking_uri("file:./mlruns")

# Create or set an experiment
mlflow.set_experiment("Iris Baseline Experiment")

solver = ["lbfgs", "newton-cg", "sag", "saga"]

for s in solver:
    # Start an MLflow run for each solver
    with mlflow.start_run():
        # Initialize and train the model
        model = Pipeline([('scaler', StandardScaler()), ('lr', LogisticRegression(random_state=42, max_iter=200, solver=s))])
        model.fit(X_train, y_train)

        # Predict on validation set
        y_val_pred = model.predict(X_val)
        #print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
        #print("Validation Classification Report:")
        #print(classification_report(y_val, y_val_pred))

        # Predict on test set
        y_test_pred = model.predict(X_test)
        #print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
        #print("Test Classification Report:")
        #print(classification_report(y_test, y_test_pred))
        
        # Log parameters
        mlflow.log_param("model_type", "LogisticRegression")
        mlflow.log_param("solver", s)
        mlflow.log_param("random_state", 42)
        mlflow.log_param("max_iter", 200)
        
        # Log metrics
        mlflow.log_metric("test_accuracy", accuracy_score(y_test, y_test_pred))
        mlflow.log_metric("test_precision_macro", classification_report(y_test, y_test_pred, output_dict=True)['macro avg']['precision'])
        mlflow.log_metric("test_recall_macro", classification_report(y_test, y_test_pred, output_dict=True)['macro avg']['recall'])
        mlflow.log_metric("test_f1_macro", classification_report(y_test, y_test_pred, output_dict=True)['macro avg']['f1-score'])
        
        # Log the model
        mlflow.sklearn.log_model(model, "model")
        
        # Get the run ID for registration
        run_id = mlflow.active_run().info.run_id

    # Register the model outside the run context
    mlflow.register_model(f"runs:/{run_id}/model", f"iris_baseline_{s}")

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/tracking/_tracking_service/utils.py:184: FutureWarning: The filesystem tracking backend (e.g., './mlruns') is deprecated as of February 2026. Consider transitioning to a database backend (e.g., 'sqlite:///mlflow.db') to take advantage of the latest MLflow features. See https://mlflow.org/docs/latest/self-hosting/migrate-from-file-store for migration guidance.
  return FileStore(store_uri, store_uri)
2026/03/03 09:34:23 INFO mlflow.tracking.fluent: Experiment with name 'Iris Baseline Experiment' does not exist. Creating a new experiment.

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.